//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public string JobID { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
        public string Distance { get; set; }
        public System.TimeSpan PickupTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public string Complete { get; set; }
        public decimal FuelCost { get; set; }
        public decimal Price { get; set; }
        public string TruckNumber { get; set; }
        public string CustomerID { get; set; }
        public string CargoID { get; set; }
        public string AbnormalLoad { get; set; }
        public string DriverID { get; set; }
    
        public virtual CargoType CargoType { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
