//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHistory
    {
        public string ServiceDate { get; set; }
        public string Engine { get; set; }
        public string PumpsAndFilters { get; set; }
        public string Transmission { get; set; }
        public string Chassis { get; set; }
        public string Cabin { get; set; }
        public string WheelsAndTyres { get; set; }
        public string Brakes { get; set; }
        public decimal Cost { get; set; }
        public string TruckNumber { get; set; }
    
        public virtual Truck Truck { get; set; }
    }
}
