//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestProject1Entities : DbContext
    {
        public TestProject1Entities()
            : base("name=TestProject1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CargoType> CargoTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Garage> Garages { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<ServiceHistory> ServiceHistories { get; set; }
        public virtual DbSet<Truck> Trucks { get; set; }
    }
}
