//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.Jobs = new HashSet<Job>();
            this.ServiceHistories = new HashSet<ServiceHistory>();
        }
    
        public string TruckNumber { get; set; }
        public string VinNumber { get; set; }
        public string LiscencePlate { get; set; }
        public string TruckStatus { get; set; }
        public string Chassis { get; set; }
        public string TruckPower { get; set; }
        public string Torque { get; set; }
        public string GearBox { get; set; }
        public string TankCapacity { get; set; }
        public string MaxLoad { get; set; }
        public string PreferredLoad { get; set; }
        public string MakeAndModel { get; set; }
        public string GarageID { get; set; }
    
        public virtual Garage Garage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceHistory> ServiceHistories { get; set; }
    }
}
